name: "❓ SLA Question"
description: "Ask a question."
title: "Replace with Your Title"
labels: [question, sla]
assignees:
  - RamyAlshurafa
  - yalla-coop-sla
body:
  - type: textarea
    attributes:
      label: "Ask your question here."
      description: "A clear and concise description of what your question is. Please note if it is connected to any existing piece of functionality."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Screenshots or a link to a Loom Recording"
      description: |
        Add any other context or screenshots about your question here. 
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
