export default {
  primaryMain: '#0C428D',
  primaryMid: '#C8DDFF',
  primaryLight: '#F7FBFF',
  secondaryMain: '#E55D3E',
  secondaryMid: '#FDDDD7',
  secondaryLight: '#FFF5F3',
  tertiaryMain: '#E55D3E',
  tertiaryMid: '#FDDDD7',
  tertiaryLight: '#FFF5F3',
  neutralPrimary: '#1A202C',
  neutralPrimaryMid: '#3A3C3F',
  neutralSecondary: '#252525',
  neutralTertiary: '#3A3F3E',
  white: '#ffffff',
};
