const primaryMain = '#FC6244';
export default {
  primaryMain,
  primaryMid: '#FDDDD7',
  primaryLight: '#FFF5F3',
  secondaryMain: '#3B557A',
  secondaryMid: '#4F6687',
  secondaryLight: '#F7FBFF',
  neutralMain: '#1A202B',
  neutralPrimaryMVP: '#1A202C',
  neutralDark: '#5A666A',
  neutralMid: '#D9D6CC',
  neutralLight: '#F4F1E5',
  neutralSurface: '#FBF9F5',
  white: '#ffffff',
  modalBackground: '#255599b3',
  error: primaryMain,
  borderPrimary: primaryMain,
  borderSecondary: '#5A666A',
  gray9: '#3C404B',
};
